### ISSUE TITLE
[proposal] sound/buf: rename to sndbuf, sbuf or something more specific than buf

### ISSUE THREAD

**Issue by mewmew** [zikichombo/sound#4]
Based on the Code Review Comments suggestions for [Package Names](https://github.com/golang/go/wiki/CodeReviewComments#package-names) and the [Package names](https://blog.golang.org/package-names) blog post.

> Packages named util, common, or misc provide clients with no sense of what the package contains. This makes it harder for clients to use the package and makes it harder for maintainers to keep the package focused.

One option would be to rename the `buf` package to `sndbuf`, `sbuf` (`sbuf` would be similarly named as `sio`) or something along those lines. This also lets clients use `buf` as a variable name without having to rename the `buf` package locally.

**Comment by wsc1** [comment]
Yes in general the package naming suggestions are good.

However, for this one I was unable to come up with a reason to decide between the alternatives such as you mention).   Also sio took a good deal of thought -- but I really didn't like sound/io and soundio seemed too long to me for something which I anticipate may be used frequently.  

Since its early, we can still change the names.  But I'd like to see if others have preferences before changing names:

Any opinions out there?
- sndbuf
- sbuf
- others?

**Comment by wsc1** [comment]
Seems unlikely we'll get other opinions, so I just renamed it.  For whatever reason, I chose sndbuf.
